// Generated by mix malachi.tokens from docs/design/design-tokens.json. Do not edit.
//
// The terminal interface's colors, one palette per color tier and theme (operator-interfaces.md
// section 8.4). Inherited fields are Color::Reset in every palette, so the terminal's own background
// and foreground show through; the PAINTED surfaces are what theme_background paints instead, both
// from one theme. The 16 color tier is declared by hand in the token file, never computed.

use ratatui::style::Color;

/// Every terminal token, in one color tier and one theme.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Palette {
    pub background: Color,
    pub foreground: Color,
    pub muted_foreground: Color,
    pub border: Color,
    pub brand_accent: Color,
    pub state_active: Color,
    pub state_sealed: Color,
    pub state_fenced: Color,
    pub state_damaged: Color,
    pub state_behind: Color,
    pub state_ahead: Color,
    pub state_blocked: Color,
    pub state_unknown: Color,
    pub chart_1: Color,
    pub chart_2: Color,
    pub chart_3: Color,
    pub chart_4: Color,
    pub chart_5: Color,
}

/// The background and foreground theme_background paints, both from one theme.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Surface {
    pub background: Color,
    pub foreground: Color,
}

pub const TRUECOLOR_LIGHT: Palette = Palette {
    background: Color::Reset,
    foreground: Color::Reset,
    muted_foreground: Color::Rgb(106, 110, 117),
    border: Color::Rgb(227, 228, 231),
    brand_accent: Color::Rgb(242, 160, 37),
    state_active: Color::Rgb(32, 162, 76),
    state_sealed: Color::Rgb(19, 118, 182),
    state_fenced: Color::Rgb(205, 126, 0),
    state_damaged: Color::Rgb(223, 30, 34),
    state_behind: Color::Rgb(180, 138, 0),
    state_ahead: Color::Rgb(145, 63, 224),
    state_blocked: Color::Rgb(171, 0, 36),
    state_unknown: Color::Rgb(110, 114, 122),
    chart_1: Color::Rgb(245, 73, 0),
    chart_2: Color::Rgb(0, 150, 137),
    chart_3: Color::Rgb(16, 78, 100),
    chart_4: Color::Rgb(255, 185, 0),
    chart_5: Color::Rgb(254, 154, 0),
};

pub const ANSI256_LIGHT: Palette = Palette {
    background: Color::Reset,
    foreground: Color::Reset,
    muted_foreground: Color::Indexed(242),
    border: Color::Indexed(254),
    brand_accent: Color::Indexed(214),
    state_active: Color::Indexed(35),
    state_sealed: Color::Indexed(31),
    state_fenced: Color::Indexed(172),
    state_damaged: Color::Indexed(160),
    state_behind: Color::Indexed(136),
    state_ahead: Color::Indexed(98),
    state_blocked: Color::Indexed(124),
    state_unknown: Color::Indexed(243),
    chart_1: Color::Indexed(202),
    chart_2: Color::Indexed(30),
    chart_3: Color::Indexed(23),
    chart_4: Color::Indexed(214),
    chart_5: Color::Indexed(208),
};

pub const TRUECOLOR_DARK: Palette = Palette {
    background: Color::Reset,
    foreground: Color::Reset,
    muted_foreground: Color::Rgb(158, 162, 170),
    border: Color::Rgb(41, 43, 46),
    brand_accent: Color::Rgb(242, 160, 37),
    state_active: Color::Rgb(57, 185, 95),
    state_sealed: Color::Rgb(73, 161, 228),
    state_fenced: Color::Rgb(242, 160, 36),
    state_damaged: Color::Rgb(247, 82, 79),
    state_behind: Color::Rgb(237, 193, 58),
    state_ahead: Color::Rgb(176, 109, 252),
    state_blocked: Color::Rgb(208, 30, 60),
    state_unknown: Color::Rgb(124, 128, 136),
    chart_1: Color::Rgb(20, 71, 230),
    chart_2: Color::Rgb(0, 188, 125),
    chart_3: Color::Rgb(254, 154, 0),
    chart_4: Color::Rgb(173, 70, 255),
    chart_5: Color::Rgb(255, 32, 87),
};

pub const ANSI256_DARK: Palette = Palette {
    background: Color::Reset,
    foreground: Color::Reset,
    muted_foreground: Color::Indexed(247),
    border: Color::Indexed(235),
    brand_accent: Color::Indexed(214),
    state_active: Color::Indexed(71),
    state_sealed: Color::Indexed(39),
    state_fenced: Color::Indexed(214),
    state_damaged: Color::Indexed(203),
    state_behind: Color::Indexed(221),
    state_ahead: Color::Indexed(135),
    state_blocked: Color::Indexed(160),
    state_unknown: Color::Indexed(244),
    chart_1: Color::Indexed(26),
    chart_2: Color::Indexed(36),
    chart_3: Color::Indexed(208),
    chart_4: Color::Indexed(135),
    chart_5: Color::Indexed(197),
};

pub const ANSI16: Palette = Palette {
    background: Color::Reset,
    foreground: Color::Reset,
    muted_foreground: Color::DarkGray,
    border: Color::DarkGray,
    brand_accent: Color::Yellow,
    state_active: Color::LightGreen,
    state_sealed: Color::Blue,
    state_fenced: Color::Yellow,
    state_damaged: Color::LightRed,
    state_behind: Color::LightYellow,
    state_ahead: Color::LightMagenta,
    state_blocked: Color::Red,
    state_unknown: Color::DarkGray,
    chart_1: Color::LightBlue,
    chart_2: Color::LightCyan,
    chart_3: Color::LightMagenta,
    chart_4: Color::LightYellow,
    chart_5: Color::LightGreen,
};

pub const PAINTED_TRUECOLOR_LIGHT: Surface = Surface {
    background: Color::Rgb(249, 250, 251),
    foreground: Color::Rgb(23, 24, 27),
};

pub const PAINTED_TRUECOLOR_DARK: Surface = Surface {
    background: Color::Rgb(13, 13, 15),
    foreground: Color::Rgb(242, 242, 244),
};

pub const PAINTED_ANSI256_LIGHT: Surface = Surface {
    background: Color::Indexed(231),
    foreground: Color::Indexed(234),
};

pub const PAINTED_ANSI256_DARK: Surface = Surface {
    background: Color::Indexed(233),
    foreground: Color::Indexed(255),
};

pub const PAINTED_ANSI16_LIGHT: Surface = Surface {
    background: Color::White,
    foreground: Color::Black,
};

pub const PAINTED_ANSI16_DARK: Surface = Surface {
    background: Color::Black,
    foreground: Color::White,
};
