defmodule Malachi.UI.TokenGen.Emit do
  @moduledoc """
  Renders the four generated files from a `Malachi.UI.TokenGen.Model`.

  Every renderer reads the model and nothing else, writes tokens in the token file's order, and
  carries no timestamp, so the same token file always produces the same bytes and the `--check` gate
  can compare them.

    * `css/1`, `assets/src/styles/tokens.css`: every web token on `:root`, the themed colors again
      for dark, one class per density mode, the reduced motion overrides, and the Tailwind v4
      `@theme inline` mapping of every color.
    * `rust/1`, `tui/src/theme/generated.rs`: a `Palette` per color tier and theme over the terminal
      tokens, and the `Surface` that `theme_background` paints.
    * `elixir/1`, `lib/malachi/ui/tokens.ex`: `Malachi.UI.Tokens`, every value resolved.
    * `snapshot/1`, `docs/design/tokens.snapshot.json`: the flat, language neutral view the contract
      tests compare the other three against.
  """

  alias Jason.OrderedObject
  alias Malachi.UI.TokenGen.Model

  @header "Generated by mix malachi.tokens from docs/design/design-tokens.json. Do not edit."

  # The repository's .formatter.exs line length, so the generated module is already what `mix format`
  # leaves. A test formats the committed module with the project's own formatter and fails if they part.
  @line_length 120

  @doc "Renders `tokens.css`."
  @spec css(Model.t()) :: String.t()
  def css(%Model{entries: entries}) do
    web = Enum.filter(entries, &(:web in &1.platforms))

    blocks =
      [
        "/* #{@header} */",
        block(":root", for(e <- web, do: {e.name, e.web.light})),
        block(~s(.dark,\n[data-theme="dark"]), for(e <- web, e.redeclare.dark, do: {e.name, e.web.dark}))
      ] ++
        mode_blocks(web) ++
        reduced_motion_block(web) ++
        [block("@theme inline", for(e <- web, e.type == :color, do: {"color-#{e.name}", "var(--#{e.name})"}))]

    Enum.join(blocks, "\n\n") <> "\n"
  end

  defp block(selector, declarations, indent \\ "") do
    body = Enum.map_join(declarations, "", fn {name, value} -> "#{indent}  --#{name}: #{value};\n" end)
    "#{indent}#{selector} {\n#{body}#{indent}}"
  end

  defp mode_blocks(web) do
    modes = web |> Enum.flat_map(fn e -> Enum.map(e.modes, &elem(&1, 0)) end) |> Enum.uniq()

    for mode <- modes do
      block(".density-#{mode}", for(e <- web, value = mode_value(e, mode), do: {e.name, value}))
    end
  end

  # A token that declares the mode takes its alternative value; one built from such a token is declared
  # again with its own value, so its var() is resolved where the class applies.
  defp mode_value(entry, mode) do
    case List.keyfind(entry.modes, mode, 0) do
      {^mode, expr} -> expr
      nil -> if mode in entry.redeclare.modes, do: entry.web.light
    end
  end

  defp reduced_motion_block(web) do
    case for e <- web, e.reduced_motion, do: {e.name, e.reduced_motion} do
      [] -> []
      declarations -> ["@media (prefers-reduced-motion: reduce) {\n" <> block(":root", declarations, "  ") <> "\n}"]
    end
  end

  @doc "Renders `generated.rs`."
  @spec rust(Model.t()) :: String.t()
  def rust(%Model{entries: entries, source: source} = model) do
    tui = Enum.filter(entries, &(:tui in &1.platforms))
    background = Model.fetch!(model, source.terminal.inherited.background)
    foreground = Model.fetch!(model, source.terminal.inherited.foreground)

    palettes =
      for theme <- [:light, :dark] do
        [
          palette("TRUECOLOR_#{upcase(theme)}", tui, &truecolor(&1, theme)),
          palette("ANSI256_#{upcase(theme)}", tui, &indexed(&1, theme))
        ]
      end

    surfaces =
      for {tier, value} <- [
            {"TRUECOLOR", fn entry, theme -> rgb(entry.color[theme].srgb8) end},
            {"ANSI256", fn entry, theme -> "Color::Indexed(#{entry.ansi256[theme]})" end},
            {"ANSI16", fn entry, theme -> painted16(source, entry, background, theme) end}
          ],
          theme <- [:light, :dark] do
        surface("PAINTED_#{tier}_#{upcase(theme)}", [
          {"background", value.(background, theme)},
          {"foreground", value.(foreground, theme)}
        ])
      end

    Enum.join(
      [
        """
        // #{@header}
        //
        // The terminal interface's colors, one palette per color tier and theme (operator-interfaces.md
        // section 8.4). Inherited fields are Color::Reset in every palette, so the terminal's own background
        // and foreground show through; the PAINTED surfaces are what theme_background paints instead, both
        // from one theme. The 16 color tier is declared by hand in the token file, never computed.

        use ratatui::style::Color;
        """,
        """
        /// Every terminal token, in one color tier and one theme.
        #[derive(Clone, Copy, Debug, PartialEq, Eq)]
        pub struct Palette {
        #{Enum.map_join(tui, "", &"    pub #{field(&1)}: Color,\n")}}
        """,
        """
        /// The background and foreground theme_background paints, both from one theme.
        #[derive(Clone, Copy, Debug, PartialEq, Eq)]
        pub struct Surface {
            pub background: Color,
            pub foreground: Color,
        }
        """
      ] ++ List.flatten(palettes) ++ [palette("ANSI16", tui, & &1.ansi16.ratatui)] ++ surfaces,
      "\n"
    )
  end

  defp palette(name, entries, value) do
    "pub const #{name}: Palette = Palette {\n" <>
      Enum.map_join(entries, "", &"    #{field(&1)}: #{value.(&1)},\n") <> "};\n"
  end

  defp surface(name, fields) do
    "pub const #{name}: Surface = Surface {\n" <>
      Enum.map_join(fields, "", fn {field, value} -> "    #{field}: #{value},\n" end) <> "};\n"
  end

  defp truecolor(%{inherited: true}, _theme), do: "Color::Reset"
  defp truecolor(entry, theme), do: rgb(entry.color[theme].srgb8)

  defp indexed(%{inherited: true}, _theme), do: "Color::Reset"
  defp indexed(entry, theme), do: "Color::Indexed(#{entry.ansi256[theme]})"

  defp painted16(source, entry, background, theme) do
    role = if entry.path == background.path, do: :background, else: :foreground
    source.terminal.painted16[theme][role].ratatui
  end

  defp rgb({r, g, b}), do: "Color::Rgb(#{r}, #{g}, #{b})"

  defp field(entry), do: String.replace(entry.name, "-", "_")

  defp upcase(theme), do: theme |> Atom.to_string() |> String.upcase()

  @doc "Renders `tokens.ex`, formatted the way `mix format` leaves it."
  @spec elixir(Model.t()) :: String.t()
  def elixir(%Model{entries: entries}) do
    tokens = Enum.filter(entries, &(:elixir in &1.platforms))

    literal =
      Enum.map_join(tokens, ", ", fn e ->
        "#{inspect(e.name)} => %{type: :#{e.type}, light: #{inspect(e.value.light)}, dark: #{inspect(e.value.dark)}}"
      end)

    source = """
    defmodule Malachi.UI.Tokens do
      # #{@header}

      @moduledoc \"\"\"
      The design tokens, for any page the server renders itself.

      Generated from `docs/design/design-tokens.json` by `mix malachi.tokens`; change the token file and
      regenerate rather than editing this module. Every value is the CSS a stylesheet would write for that
      token in that theme, with every reference already resolved, since a page rendered here has no
      stylesheet cascade to resolve a `var()` against.
      \"\"\"

      @tokens %{#{literal}}

      @names #{inspect(Enum.map(tokens, & &1.name), limit: :infinity)}

      @typedoc "A token: its type and its CSS value in each theme."
      @type token :: %{type: atom(), light: String.t(), dark: String.t()}

      @doc "Every token, by name."
      @spec all() :: %{String.t() => token()}
      def all, do: @tokens

      @doc "Every token name, in the token file's order."
      @spec names() :: [String.t()]
      def names, do: @names

      @doc "A token's CSS value in a theme, or `:error` for a name that is not a token."
      @spec get(String.t(), :light | :dark) :: {:ok, String.t()} | :error
      def get(name, theme) when theme in [:light, :dark] do
        case Map.fetch(@tokens, name) do
          {:ok, token} -> {:ok, Map.fetch!(token, theme)}
          :error -> :error
        end
      end
    end
    """

    source |> Code.format_string!(line_length: @line_length) |> IO.iodata_to_binary() |> Kernel.<>("\n")
  end

  @doc "Renders `tokens.snapshot.json`."
  @spec snapshot(Model.t()) :: String.t()
  def snapshot(%Model{entries: entries, source: source} = model) do
    inherited = source.terminal.inherited

    document =
      object([
        {"$description",
         "#{@header} The flat, language neutral view of every token that the cross language contract tests compare each generated file against."},
        {"tokens", object(Enum.map(entries, &{&1.name, snapshot_entry(&1)}))},
        {"terminal",
         object([
           {"inherited",
            object([
              {"background", Model.fetch!(model, inherited.background).name},
              {"foreground", Model.fetch!(model, inherited.foreground).name}
            ])},
           {"painted16",
            object(
              for theme <- ~w(light dark)a do
                {Atom.to_string(theme),
                 object(
                   for role <- ~w(background foreground)a do
                     {Atom.to_string(role), ansi16(source.terminal.painted16[theme][role])}
                   end
                 )}
              end
            )}
         ])}
      ])

    Jason.encode!(document, pretty: true) <> "\n"
  end

  defp snapshot_entry(entry) do
    tui? = :tui in entry.platforms

    object(
      [
        {"path", entry.path},
        {"type", Atom.to_string(entry.type)},
        {"platforms", Enum.map(entry.platforms, &Atom.to_string/1)},
        {"themed", entry.themed},
        {"ref", entry.ref},
        {"redeclare", object([{"dark", entry.redeclare.dark}, {"modes", entry.redeclare.modes}])},
        {"light", snapshot_theme(entry, :light)},
        {"dark", snapshot_theme(entry, :dark)}
      ] ++
        if(entry.modes == [], do: [], else: [{"modes", object(entry.modes)}]) ++
        if(entry.reduced_motion, do: [{"reducedMotion", entry.reduced_motion}], else: []) ++
        if(tui?, do: [{"ansi16", ansi16(entry.ansi16)}, {"inherited", entry.inherited}], else: [])
    )
  end

  defp snapshot_theme(entry, theme) do
    color =
      case entry.color do
        nil ->
          []

        color ->
          {r, g, b} = color[theme].srgb8
          [{"srgb8", [r, g, b]}, {"alpha", color[theme].alpha}]
      end

    ansi256 = if entry.ansi256, do: [{"ansi256", entry.ansi256[theme]}], else: []
    object([{"web", entry.web[theme]}, {"value", entry.value[theme]}] ++ color ++ ansi256)
  end

  defp ansi16(%{code: code, ratatui: ratatui}) do
    object([{"code", if(code == :default, do: "default", else: code)}, {"ratatui", ratatui}])
  end

  defp object(pairs), do: %OrderedObject{values: pairs}
end
