defmodule Malachi.UI.TokenGen.EmitTest do
  use ExUnit.Case, async: true

  import Malachi.TokenFixture, only: [minimal: 0, encode!: 1, put: 3]

  alias Malachi.UI.TokenGen
  alias Mix.Tasks.Format

  @header "Generated by mix malachi.tokens from docs/design/design-tokens.json. Do not edit."

  defp generate(file \\ minimal()) do
    assert {:ok, outputs} = TokenGen.generate(encode!(file))
    Map.new(outputs)
  end

  test "names the four outputs, in a fixed order" do
    assert TokenGen.outputs() == [
             "assets/src/styles/tokens.css",
             "tui/src/theme/generated.rs",
             "lib/malachi/ui/tokens.ex",
             "docs/design/tokens.snapshot.json"
           ]

    assert {:ok, outputs} = TokenGen.generate(encode!(minimal()))
    assert Enum.map(outputs, &elem(&1, 0)) == TokenGen.outputs()
  end

  test "generation is byte for byte deterministic and ends every file with one newline" do
    first = generate()
    assert first == generate()

    for {path, content} <- first do
      assert String.ends_with?(content, "\n") and not String.ends_with?(content, "\n\n"), path
      assert content =~ @header, path
      refute content =~ "\u2014", path
    end
  end

  test "a broken file or a failed gate is an error, not a partial output" do
    assert {:error, [_ | _]} = TokenGen.generate("{")

    low = put(minimal(), ["color", "state", "on", "light"], "oklch(0.900 0.050 149.2)")
    assert {:error, errors} = TokenGen.generate(encode!(low))
    assert Enum.any?(errors, &(&1 =~ "$contrast"))
  end

  describe "tokens.css" do
    setup do: %{css: generate()["assets/src/styles/tokens.css"]}

    test "declares every token on :root, references as var()", %{css: css} do
      assert css =~ ":root {\n  --background: oklch(0.985 0.002 265);\n"
      assert css =~ "  --text-body: var(--foreground);\n"
      assert css =~ ~s(  --font-sans: system-ui, "Segoe UI", sans-serif;\n)
      assert css =~ "  --type-body: var(--weight-regular) var(--text-base)/var(--leading-normal) var(--font-sans);\n"
      assert css =~ "  --shadow-xs: 0px 1px 2px -1px var(--shadow-color-soft);\n"
      assert css =~ "  --row-height: var(--row-default);\n"
      assert css =~ "  --ease-standard: cubic-bezier(0.2, 0, 0, 1);\n"
    end

    test "redeclares for dark every token a theme changes, including aliases and shadows", %{css: css} do
      [_, dark] = String.split(css, ~s(.dark,\n[data-theme="dark"] {\n), parts: 2)
      [dark | _] = String.split(dark, "}", parts: 2)
      assert dark =~ "  --background: oklch(0.161 0.004 265);\n"
      # An alias resolves on the element that declares it, so a dark subtree needs it declared again.
      assert dark =~ "  --text-body: var(--foreground);\n"
      assert dark =~ "  --shadow-xs: 0px 1px 2px -1px var(--shadow-color-soft);\n"
      refute dark =~ "--space-1"
      refute dark =~ "--type-body"
    end

    test "writes no reduced motion block when no token declares one" do
      file = Malachi.TokenFixture.delete(minimal(), ["motion", "fast", "$reducedMotion"])
      refute generate(file)["assets/src/styles/tokens.css"] =~ "prefers-reduced-motion"
    end

    test "redeclares in a density class every token that depends on a moded one" do
      file =
        put(minimal(), ["density", "row", "gap"], Malachi.TokenFixture.object([{"$value", "{density.row.height}"}]))

      css = generate(file)["assets/src/styles/tokens.css"]
      assert css =~ ".density-compact {\n  --row-height: var(--row-compact);\n  --row-gap: var(--row-height);\n}\n"
    end

    test "writes one class per density mode, the reduced motion block and the Tailwind theme", %{css: css} do
      assert css =~ ".density-compact {\n  --row-height: var(--row-compact);\n}\n"
      assert css =~ "@media (prefers-reduced-motion: reduce) {\n  :root {\n    --motion-fast: 0ms;\n  }\n}\n"
      assert css =~ "@theme inline {\n  --color-background: var(--background);\n"
      assert css =~ "  --color-text-body: var(--text-body);\n"
      refute css =~ "--color-space-1"
    end
  end

  describe "generated.rs" do
    setup do: %{rust: generate()["tui/src/theme/generated.rs"]}

    test "declares one field per terminal token and every tier per theme", %{rust: rust} do
      assert rust =~ "use ratatui::style::Color;\n"

      assert rust =~
               "pub struct Palette {\n    pub background: Color,\n    pub foreground: Color,\n    pub state_on: Color,"

      for name <- ~w(TRUECOLOR_LIGHT TRUECOLOR_DARK ANSI256_LIGHT ANSI256_DARK ANSI16) do
        assert rust =~ "pub const #{name}: Palette = Palette {\n"
      end

      for name <-
            ~w(PAINTED_TRUECOLOR_LIGHT PAINTED_TRUECOLOR_DARK PAINTED_ANSI256_LIGHT PAINTED_ANSI256_DARK PAINTED_ANSI16_LIGHT PAINTED_ANSI16_DARK) do
        assert rust =~ "pub const #{name}: Surface = Surface {\n"
      end
    end

    test "inherits the terminal's background and foreground in every palette, and paints them per theme", %{rust: rust} do
      [truecolor | _] = rust |> String.split("pub const TRUECOLOR_LIGHT: Palette = Palette {\n") |> tl()
      assert truecolor =~ "    background: Color::Reset,\n    foreground: Color::Reset,\n    state_on: Color::Rgb("

      assert rust =~
               "pub const PAINTED_ANSI16_DARK: Surface = Surface {\n    background: Color::Black,\n    foreground: Color::White,\n};"

      assert rust =~
               ~r/pub const PAINTED_TRUECOLOR_LIGHT: Surface = Surface \{\n    background: Color::Rgb\(\d+, \d+, \d+\),/
    end

    test "writes the 16 color tier exactly as declared", %{rust: rust} do
      assert rust =~
               "pub const ANSI16: Palette = Palette {\n    background: Color::Reset,\n    foreground: Color::Reset,\n    state_on: Color::LightGreen,\n    state_off: Color::LightRed,"
    end
  end

  describe "tokens.ex" do
    setup do: %{elixir: generate()["lib/malachi/ui/tokens.ex"]}

    test "is formatted, parses, and holds resolved values", %{elixir: elixir} do
      {format, _options} = Format.formatter_for_file("lib/malachi/ui/tokens.ex")
      assert format.(elixir) == elixir
      assert {:ok, _ast} = Code.string_to_quoted(elixir)

      assert elixir =~
               ~r/"text-body" => %\{\s*type: :color,\s*light: "oklch\(0\.210 0\.006 265\)",\s*dark: "oklch\(0\.962 0\.002 265\)"\s*\}/

      assert elixir =~ "defmodule Malachi.UI.Tokens do"
    end
  end

  describe "tokens.snapshot.json" do
    setup do: %{snapshot: Jason.decode!(generate()["docs/design/tokens.snapshot.json"])}

    test "carries every token flat, by name, in the token file's order", %{snapshot: snapshot} do
      on = snapshot["tokens"]["state-on"]
      assert on["path"] == "color.state.on"
      assert on["platforms"] == ["web", "elixir", "tui"]
      assert on["light"]["web"] == "oklch(0.627 0.165 149.2)"
      assert [_, _, _] = on["light"]["srgb8"]
      assert on["light"]["alpha"] == 1.0
      assert is_integer(on["dark"]["ansi256"])
      assert on["ansi16"] == %{"code" => 10, "ratatui" => "Color::LightGreen"}
      assert on["inherited"] == false

      assert snapshot["tokens"]["text-body"]["ref"] == "foreground"
      assert snapshot["tokens"]["row-height"]["modes"] == %{"compact" => "var(--row-compact)"}
      assert snapshot["tokens"]["motion-fast"]["reducedMotion"] == "0ms"
      assert snapshot["terminal"]["inherited"] == %{"background" => "background", "foreground" => "foreground"}
      assert snapshot["terminal"]["painted16"]["light"]["background"] == %{"code" => 15, "ratatui" => "Color::White"}
    end
  end
end
